### ISSUE TITLE
Hello, I have a problem in using pysrcds. Can you help me solve it?

### ISSUE THREAD

**Issue by handsomehahh** [pmrowla/pysrcds#6]
- 

1.    when i try to connect to my rust server ,it run error ,I tried to find the error, but there was nothing I could do.
File "G:\codes\demo\venv\lib\site-packages\srcds\rcon.py", line 134, in read_response
    raise RconError('Response ID does not match request ID')
srcds.rcon.RconError: Response ID does not match request ID
2. Now that the rust server is websocket rcon, can you help change the code to connect with websoket rcon

**Comment by pmrowla** [comment]
This library is not really developed any more, and I can't find any documentation on how the rust websocket rcon works. It also looks like there are several other libraries and tools for doing rust rcon, I would suggest you try one of those.
